# Generated by Django 2.2.16 on 2023-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230429_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2023-04-29 16:05:53.582315'),
        ),
    ]
